spring:
  data:
    mongodb:
      uri: mongodb+srv://alosh:gw262So1oNnL0RcM@cluster0.n4tzi9k.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: productsdb
  application:
    name: product-service

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
